# Generated by Django 4.0 on 2022-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=3000)),
            ],
        ),
    ]
